# -*- coding: utf-8 -*-
"""5주차_동적계획법_지용2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1at3v7R4S3nGyGTGoeLvyMMPSwkRaxx8f
"""

# https://github.com/tadvi/uva/blob/master/UVa%2010943%20how%20do%20you%20add/sample/main.py

import sys
import numpypy as np

memo = np.zeros((101, 101), dtype=np.int)
memo.fill(-1)
for i in range(101):
    memo[0, i] = 1
    memo[i, 1] = 1


def dp(n, k):
    if memo[n, k] != -1:
        return memo[n, k]
    memo[n, k] = 0
    for i in range(n + 1):
        memo[n, k] += dp(n - i, k - 1)
        memo[n, k] %= 1000000
    return memo[n, k]

sys.stdin = open('input.txt')
while True:
    n, k = map(int, raw_input().split())
    if not n and not k:
        break
    print dp(n, k)