# -*- coding: utf-8 -*-
"""5주차_동적계획법_주원2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1at3v7R4S3nGyGTGoeLvyMMPSwkRaxx8f
"""

V = [6,2,5,5,4,5,6,3,7,6,6]
for _ in range(int(input())):
    N = int(input())
    DP = [[[-1]*2 for i in range(N+1)] for j in range(N+1)]
    def match(N,K,firstpos):
        if K == 0: return N == 0
        if N <= 0: return False
        if DP[N][K][firstpos] != -1: return DP[N][K][firstpos]
        DP[N][K][firstpos] = False
        for i in range(10):
            if firstpos == 1 and i == 0: continue
            if match(N-V[i], K-1,0):
                DP[N][K][firstpos] = True
                break
        return DP[N][K][firstpos]
    def g(N, K, firstpos):
        if K == 0: return ''
        for i in range(10):
            if firstpos == 1 and i == 0: continue
            if match(N-V[i], K-1, 0):
                return str(i) + g(N-V[i],K-1,0)
    for i in range(100):
        if match(N, i, 1):
            print(g(N, i, 1), end=' ')
            break
    a = N % 2
    b = (N-a*3) // 2
    print('7'*a + '1'*b)