# -*- coding: utf-8 -*-
"""5주차_구현_미경1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1at3v7R4S3nGyGTGoeLvyMMPSwkRaxx8f
"""

N = input()

def calc(n):
    if len(n) == 1 or n == '10':
        return int(n) - 1

    tmp = int(n[:2])
    if (tmp >= 11) and (tmp < 20):
        return n[1:] + (n[1:])[::-1]

    elif tmp == 10:
        return '9' + n[2:-1] + (n[2:])[::-1] + '9'

    else:
        f = str(int(n[0]) - 1)
        return f + n[1:-1] + (n[1:])[::-1] + f


print(calc(N))