# -*- coding: utf-8 -*-
"""7주차_분할정복1_지용

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VR-MHSixMi1fF-tIrXsam9hbPAJyKJDK
"""

while True:
	n = list(map(int, input().split())) + [0]
	N = n[0]
	if N == 0: break

	s = [(1, n[1])]
	ans = 0

	for i in range(2, N+2):
		x = i
		while s and s[-1][1] > n[i]:
			x,h = s.pop()
			ans = max(ans, (i-x)*h)
		s.append((x, n[i]))		

	print(ans)