# -*- coding: utf-8 -*-
"""7주차_분할정복2_유민

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VR-MHSixMi1fF-tIrXsam9hbPAJyKJDK
"""

N=int(input())
p=[]

for i in range(N):
  p.append([*map(int, input().split())])
p.sort()

def d(pi, pj):
  xi,yi=pi; xj,yj=pj
  return (xi-xj)**2+(yi-yj)**2
M = 10 ** 9

def dm(a, b):
  global M
  m = M
  if b-a == 1: 
    return M
  if b-a == 2: 
    return d(p[a], p[a+1])
  c = (a+b) // 2
  m = min(dm(a, c), dm(c, b))
  pm = [*filter(lambda pi: (pi[0]-p[c][0])**2<m, p[a:b])]
  pm.sort(key=lambda pi: pi[1])

  for i in range(len(pm)):
    for j in range(i+1, len(pm)):
      if (pm[i][1]-pm[j][1])**2>=m: break
      m = min(m, d(pm[i], pm[j]))
  return m
print(dm(0, n))