# -*- coding: utf-8 -*-
"""7주차_구현_지용

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VR-MHSixMi1fF-tIrXsam9hbPAJyKJDK
"""

N = int(input())

for i in range(N):
    _ = input()
    
    x = list(map(int, input().split("/")))
    y = list(map(int, input().split("/")))
    
    if x[2]*365+x[1]*30+x[0] < y[2]*365+y[1]*30+y[0]:
        print("Case #{}: Invalid birth date".format(i+1))
        continue
    
    age = x[2] - y[2]
    if x[1] < y[1]:
        age -= 1
    elif x[1] == y[1] and x[0] < y[0]:
        age -= 1
    
    if age > 130:
        print("Case #{}: Check birth date".format(i+1))
    else:
        print("Case #{}: {}".format(i+1, age))